### ISSUE TITLE
MD of SOS Service

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/starterkit#21] opened 2014-08-08 07:35 UTC
GetCapabilities request, on the SOS service, return with same information for all SK. This MD are not updated with the information filled during the registration.
<ows:ServiceProvider>
  <ows:ProviderName>CNR-ISMAR</ows:ProviderName>
  <ows:ProviderSite xlink:href="None"/>
  <ows:ServiceContact>
    <ows:IndividualName>CNR-ISMAR</ows:IndividualName>
    <ows:PositionName>None</ows:PositionName>
    <ows:ContactInfo>
      <ows:Phone>
        <ows:Voice>None</ows:Voice>
      </ows:Phone>
    <ows:Address>
      <ows:DeliveryPoint>None</ows:DeliveryPoint>
      <ows:City>None</ows:City>
      <ows:AdministrativeArea>None</ows:AdministrativeArea>
      <ows:PostalCode>None</ows:PostalCode>
      <ows:Country>None</ows:Country>
      <ows:ElectronicMailAddress>help.skritmare@irea.cnr.it</ows:ElectronicMailAddress>
    </ows:Address>
  </ows:ContactInfo>
</ows:ServiceContact>
</ows:ServiceProvider>

**Comment by menegon** [comment] 2015-03-31 19:41
Closing as duplicate of #22

**Comment by menegon** [comment] 2015-03-31 19:42
Closing as duplicate of #22

**Closed by menegon** 2015-03-31 19:42 UTC
Labels: critical, tutti_sk
